name: myapp
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^2.32.0
  cloud_firestore: ^4.17.5
  firebase_storage: ^11.7.7
  firebase_auth: ^4.6.3
  firebase_messaging: ^14.7.9
  flutter_local_notifications: ^17.2.3
  google_sign_in: ^6.1.1
  shared_preferences: ^2.2.3
  flutter_svg: ^2.0.10+1
  flutter_facebook_auth: ^6.0.4
  image_picker: ^1.2.0
  google_maps_flutter: ^2.13.1
  google_fonts: ^6.3.2
  firebase_app_check: ^0.2.2+7
  screenshot: ^3.0.0
  geolocator: ^10.1.0
  google_mlkit_commons: ^0.11.0
  google_mlkit_text_recognition: ^0.15.0
  http: ^1.1.0
  geocoding: ^4.0.0
  signature: ^5.4.1
  # printing: 5.13.1  # Temporarily disabled due to Android build conflict with lStar attribute
  pdf: ^3.10.8
  file_saver: ^0.2.12
  image: ^4.2.0
  intl: ^0.20.2
  qr_flutter: ^4.1.0
  blue_thermal_printer: ^1.2.3
  mobile_scanner: ^7.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4
  change_app_package_name: ^1.5.0

flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/file_000000008fc872089268acc9b04e5bcf.png"
  remove_alpha_ios: true
  web:
    generate: true
    image_path: "assets/file_000000008fc872089268acc9b04e5bcf.png"
    background_color: "#ffffff"
    theme_color: "#ffffff"
  windows:
    generate: true
    image_path: "assets/file_000000008fc872089268acc9b04e5bcf.png"
  macos:
    generate: true
    image_path: "assets/file_000000008fc872089268acc9b04e5bcf.png"
